### ISSUE TITLE
plot trajectory based on bin means for multiple texts

### ISSUE THREAD

**Issue by cownr10r** [mjockers/syuzhet#17]
Dear Dr. Jockers,

Is there a way to have syuzhet ingest multiple texts (143), calculate sentiment and plot the trajectory? It seems I can only code for one text at a time.

**Comment by mjockers** [comment]
Currently no, but this is an interesting idea.  I assume that you would want to be able to identify the boundaries between texts in the resulting sentiment arc?  

In the meantime, you could achieve this end by simply combining the various documents into a single text file.  I did exactly this when I was exploring a couple of trilogies and wanted to see the overall arc of the series.

**Comment by cownr10r** [comment]
Thanks, Dr. Jockers. I appreciate your feedback!

**Comment by mjockers** [comment]
Here is a hack to do what I think you are looking for.  Not sure how this will scale to 143 books.  

Basically this code stitches together a series of texts from a directory (so order will be alpha), gets the sentiments and then creates a plot with markers (vertical lines) that show each text boundary.  In the first example, the smoother considers all the tests as one long text, so you don't get abrupt text boundaries.  In the second example, you can see the abrupt boundaries since smoothing is local to each book.

`corpus_path <- "/Users/mjockers/Documents/Research/Corpora/Woolf/completedTXTFiles/fiction"
corpus_files <- dir(corpus_path)[c(1,6,12,14)]

# Example 1, merging all the texts into one long one.
all_sentiments <- NULL # empty bucket
all_lengths <- NULL # empty bucket for saving the length of each book in sentences.
for(i in 1:length(corpus_files)){
  file_in <- get_text_as_string(file.path(corpus_path, corpus_files[i]))
  sentences <- get_sentences(file_in)
  sentiment <- get_sentiment(sentences)
  all_sentiments <- c(all_sentiments, sentiment)
  all_lengths <- c(all_lengths, length(sentiment))
  cat("done with", corpus_files[i], "\n")
}

# Now create a plot with markers for each text boundary based on the values in all_lengths object.
smoothed_books <- get_dct_transform(all_sentiments, low_pass_size = 5, x_reverse_len = length(all_sentiments), scale_vals = FALSE, scale_range = TRUE)
plot(smoothed_books, type = "l")
abline(v = cumsum(head(all_lengths, -1)))

# Example 2: Merges each text after smoothing.
all_sentiments <- NULL # empty bucket
all_lengths <- NULL # empty bucket for saving the length of each book in sentences.
for(i in 1:length(corpus_files)){
  file_in <- get_text_as_string(file.path(corpus_path, corpus_files[i]))
  sentences <- get_sentences(file_in)
  sentiment <- get_sentiment(sentences)
  smoothed_sentiments <- get_dct_transform(sentiment, low_pass_size = 5, x_reverse_len = length(sentiment), scale_vals = FALSE, scale_range = TRUE)
  all_sentiments <- c(all_sentiments, smoothed_sentiments)
  all_lengths <- c(all_lengths, length(smoothed_sentiments))
  cat("done with", corpus_files[i], "\n")
}

# Now create a plot with markers for each text boundary based on the values in all_lengths object.
plot(all_sentiments, type = "l")
abline(v = cumsum(head(all_lengths, -1)))`
![rplot1](https://user-images.githubusercontent.com/3277598/28735247-07cbc772-73aa-11e7-8529-4fc64c0493ae.jpeg)
![rplot2](https://user-images.githubusercontent.com/3277598/28735252-0bfde582-73aa-11e7-962b-bdfb4a8a3145.jpeg)
